# Generated by Django 2.1.5 on 2021-03-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='newfeature',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
